# coding: utf-8

"""
NVIDIA Run:ai

# Introduction  The NVIDIA Run:ai Control-Plane API reference is a guide that provides an easy-to-use programming interface for adding various tasks to your application, including workload submission, resource management, and administrative operations.  NVIDIA Run:ai APIs are accessed using *bearer tokens*. To obtain a token, you need to create a **Service account** through the NVIDIA Run:ai user interface. To create a service account, in your UI, go to Access → Service Accounts (for organization-level service accounts) or User settings → Access Keys (for user access keys), and create a new one.  After you have created a new service account, you will need to assign it access rules. To assign access rules to the service account, see [Create access rules](https://run-ai-docs.nvidia.com/saas/infrastructure-setup/authentication/accessrules#create-or-delete-rules). Make sure you assign the correct rules to your service account. Use the [Roles](https://run-ai-docs.nvidia.com/saas/infrastructure-setup/authentication/roles) to assign the correct access rules.  To get your access token, follow the instructions in [Request a token](https://run-ai-docs.nvidia.com/saas/reference/api/rest-auth/#request-an-api-token).

The version of the OpenAPI document: latest
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


import unittest

from runai.api.credentials_api import CredentialsApi


class TestCredentialsApi(unittest.TestCase):
    """CredentialsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CredentialsApi()

    def tearDown(self) -> None:
        pass

    def test_create_access_key(self) -> None:
        """Test case for create_access_key

        Create an access key.
        """
        pass

    def test_create_docker_registry(self) -> None:
        """Test case for create_docker_registry

        Create a docker registry credential.
        """
        pass

    def test_create_generic_secret(self) -> None:
        """Test case for create_generic_secret

        Create a generic-secret.
        """
        pass

    def test_create_ngc_api_key(self) -> None:
        """Test case for create_ngc_api_key

        Create a ngc-api-key.
        """
        pass

    def test_create_password(self) -> None:
        """Test case for create_password

        Create a userid / password credential.
        """
        pass

    def test_delete_access_key(self) -> None:
        """Test case for delete_access_key

        Delete an access key.
        """
        pass

    def test_delete_docker_registry(self) -> None:
        """Test case for delete_docker_registry

        Delete a docker registry credential.
        """
        pass

    def test_delete_generic_secret(self) -> None:
        """Test case for delete_generic_secret

        Delete a generic-secret.
        """
        pass

    def test_delete_ngc_api_key(self) -> None:
        """Test case for delete_ngc_api_key

        Delete a ngc-api-key.
        """
        pass

    def test_delete_password(self) -> None:
        """Test case for delete_password

        Delete a password asset.
        """
        pass

    def test_get_access_key_by_id(self) -> None:
        """Test case for get_access_key_by_id

        Get an access key.
        """
        pass

    def test_get_docker_registry_by_id(self) -> None:
        """Test case for get_docker_registry_by_id

        Get a docker registry credential.
        """
        pass

    def test_get_generic_secret_by_id(self) -> None:
        """Test case for get_generic_secret_by_id

        Get a generic-secret.
        """
        pass

    def test_get_ngc_api_key_by_id(self) -> None:
        """Test case for get_ngc_api_key_by_id

        Get a ngc-api-key.
        """
        pass

    def test_get_password_by_id(self) -> None:
        """Test case for get_password_by_id

        Get a userid / password credential.
        """
        pass

    def test_list_access_keys(self) -> None:
        """Test case for list_access_keys

        List access keys.
        """
        pass

    def test_list_credentials_assets(self) -> None:
        """Test case for list_credentials_assets

        List credentials.
        """
        pass

    def test_list_docker_registries(self) -> None:
        """Test case for list_docker_registries

        List docker registry credentials.
        """
        pass

    def test_list_generic_secret(self) -> None:
        """Test case for list_generic_secret

        List generic-secrets.
        """
        pass

    def test_list_ngc_api_key(self) -> None:
        """Test case for list_ngc_api_key

        List ngc-api-keys.
        """
        pass

    def test_list_passwords(self) -> None:
        """Test case for list_passwords

        List password credentials.
        """
        pass

    def test_update_access_key(self) -> None:
        """Test case for update_access_key

        Update an access key.
        """
        pass

    def test_update_docker_registry(self) -> None:
        """Test case for update_docker_registry

        Update a docker registry credential.
        """
        pass

    def test_update_generic_secret(self) -> None:
        """Test case for update_generic_secret

        Update a generic-secret.
        """
        pass

    def test_update_ngc_api_key(self) -> None:
        """Test case for update_ngc_api_key

        Update a ngc-api-key.
        """
        pass

    def test_update_password(self) -> None:
        """Test case for update_password

        Update a password credential.
        """
        pass


if __name__ == "__main__":
    unittest.main()
