# coding: utf-8

"""
Test file for SettingsApi
Generated by OpenAPI Generator with custom template
"""

import pytest
import unittest.mock as mock
from datetime import datetime, timezone
import json

from runai.configuration import Configuration
from runai.api_client import ApiClient
from runai.models import *
from runai.exceptions import ApiException


class TestSettingsApi:
    """Test cases for SettingsApi"""

    @pytest.fixture(autouse=True)
    def setup(self):
        """Setup test fixtures"""
        self.configuration = Configuration(
            client_id="test-client",
            client_secret="test-secret",
            runai_base_url="https://test.run.ai",
        )
        self.api_client = ApiClient(self.configuration)
        self.api = SettingsApi(self.api_client)

        # Mock the request method
        self.request_patcher = mock.patch.object(self.api_client.rest_client, "request")
        self.mock_request = self.request_patcher.start()
        yield
        self.request_patcher.stop()

    def test_get_security_setting_by_key(self):
        """Test case for get_security_setting_by_key

        Get security setting by key
        """
        # Mock response
        mock_response = mock.Mock()
        mock_response.status = 200
        mock_response.read.return_value = json.dumps({"data": {}})
        self.mock_request.return_value = mock_response

        # Test parameters
        key = runai.SettingsKeyEnum()  # SettingsKeyEnum | The settings key

        # Make request
        response = self.api.get_security_setting_by_key(
            key=key,
        )

        # Verify request was made
        assert self.mock_request.called
        args, kwargs = self.mock_request.call_args

        # Verify request method and URL
        assert kwargs["method"] == "GET"
        assert "/api/v1/security/settings/{key}" in kwargs["url"]

        # Verify response
        assert isinstance(response, Dict[str, object])

    def test_get_security_setting_by_key_error(self):
        """Test error handling for get_security_setting_by_key"""
        # Mock error response
        mock_response = mock.Mock()
        mock_response.status = 400
        mock_response.read.return_value = json.dumps({"message": "Error message"})
        self.mock_request.return_value = mock_response

        # Test parameters
        key = runai.SettingsKeyEnum()

        # Verify error handling
        with pytest.raises(ApiException) as exc_info:
            self.api.get_security_setting_by_key(
                key=key,
            )
        assert exc_info.value.status == 400

    def test_get_security_settings(self):
        """Test case for get_security_settings

        Get security settings
        """
        # Mock response
        mock_response = mock.Mock()
        mock_response.status = 200
        mock_response.read.return_value = json.dumps({"data": {}})
        self.mock_request.return_value = mock_response

        # Test parameters

        # Make request
        response = self.api.get_security_settings()

        # Verify request was made
        assert self.mock_request.called
        args, kwargs = self.mock_request.call_args

        # Verify request method and URL
        assert kwargs["method"] == "GET"
        assert "/api/v1/security/settings" in kwargs["url"]

        # Verify response
        assert isinstance(response, SettingsGetResponse)

    def test_get_security_settings_error(self):
        """Test error handling for get_security_settings"""
        # Mock error response
        mock_response = mock.Mock()
        mock_response.status = 400
        mock_response.read.return_value = json.dumps({"message": "Error message"})
        self.mock_request.return_value = mock_response

        # Test parameters

        # Verify error handling
        with pytest.raises(ApiException) as exc_info:
            self.api.get_security_settings()
        assert exc_info.value.status == 400

    def test_update_security_setting_by_key(self):
        """Test case for update_security_setting_by_key

        Update security setting by key
        """
        # Mock response
        mock_response = mock.Mock()
        mock_response.status = 200
        mock_response.read.return_value = json.dumps({})
        self.mock_request.return_value = mock_response

        # Test parameters
        key = runai.SettingsKeyEnum()  # SettingsKeyEnum | The settings key
        update_security_setting_by_key_request = {
            "enabled": False,
            "idpAlias": "oidc",
        }  # UpdateSecuritySettingByKeyRequest |

        # Make request
        self.api.update_security_setting_by_key(
            key=key,
            update_security_setting_by_key_request=update_security_setting_by_key_request,
        )

        # Verify request was made
        assert self.mock_request.called
        args, kwargs = self.mock_request.call_args

        # Verify request method and URL
        assert kwargs["method"] == "PUT"
        assert "/api/v1/security/settings/{key}" in kwargs["url"]

        # Verify body
        assert kwargs["body"] is not None

    def test_update_security_setting_by_key_error(self):
        """Test error handling for update_security_setting_by_key"""
        # Mock error response
        mock_response = mock.Mock()
        mock_response.status = 400
        mock_response.read.return_value = json.dumps({"message": "Error message"})
        self.mock_request.return_value = mock_response

        # Test parameters
        key = runai.SettingsKeyEnum()
        update_security_setting_by_key_request = {"enabled": False, "idpAlias": "oidc"}

        # Verify error handling
        with pytest.raises(ApiException) as exc_info:
            self.api.update_security_setting_by_key(
                key=key,
                update_security_setting_by_key_request=update_security_setting_by_key_request,
            )
        assert exc_info.value.status == 400
