# coding: utf-8

"""
NVIDIA Run:ai

# Introduction  The NVIDIA Run:ai Control-Plane API reference is a guide that provides an easy-to-use programming interface for adding various tasks to your application, including workload submission, resource management, and administrative operations.  NVIDIA Run:ai APIs are accessed using *bearer tokens*. To obtain a token, you need to create a **Service account** through the NVIDIA Run:ai user interface. To create a service account, in your UI, go to Access → Service Accounts (for organization-level service accounts) or User settings → Access Keys (for user access keys), and create a new one.  After you have created a new service account, you will need to assign it access rules. To assign access rules to the service account, see [Create access rules](https://run-ai-docs.nvidia.com/saas/infrastructure-setup/authentication/accessrules#create-or-delete-rules). Make sure you assign the correct rules to your service account. Use the [Roles](https://run-ai-docs.nvidia.com/saas/infrastructure-setup/authentication/roles) to assign the correct access rules.  To get your access token, follow the instructions in [Request a token](https://run-ai-docs.nvidia.com/saas/reference/api/rest-auth/#request-an-api-token).

The version of the OpenAPI document: latest
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


import unittest

from runai.api.researcher_command_line_interface_deprecated_api import (
    ResearcherCommandLineInterfaceDeprecatedApi,
)


class TestResearcherCommandLineInterfaceDeprecatedApi(unittest.TestCase):
    """ResearcherCommandLineInterfaceDeprecatedApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ResearcherCommandLineInterfaceDeprecatedApi()

    def tearDown(self) -> None:
        pass

    def test_get_binary_deprecated(self) -> None:
        """Test case for get_binary_deprecated

        Download RunAI Researcher command line binary
        """
        pass

    def test_get_installer_linux_commands_deprecated(self) -> None:
        """Test case for get_installer_linux_commands_deprecated

        Get Linux installer script commands
        """
        pass

    def test_get_installer_linux_deprecated(self) -> None:
        """Test case for get_installer_linux_deprecated

        Download Linux installer script
        """
        pass

    def test_get_installer_mac_commands_deprecated(self) -> None:
        """Test case for get_installer_mac_commands_deprecated

        Get Mac installer script commands
        """
        pass

    def test_get_installer_mac_deprecated(self) -> None:
        """Test case for get_installer_mac_deprecated

        Download Mac installer script
        """
        pass

    def test_get_installer_unix_commands_deprecated(self) -> None:
        """Test case for get_installer_unix_commands_deprecated

        Get Unix installer script commands
        """
        pass

    def test_get_installer_unix_deprecated(self) -> None:
        """Test case for get_installer_unix_deprecated

        Download Unix installer script
        """
        pass

    def test_get_installer_windows_commands_deprecated(self) -> None:
        """Test case for get_installer_windows_commands_deprecated

        Get Windows MSI installer script commands
        """
        pass

    def test_get_manual_document_deprecated(self) -> None:
        """Test case for get_manual_document_deprecated

        Get CLI document by name
        """
        pass


if __name__ == "__main__":
    unittest.main()
