# coding: utf-8

"""
NVIDIA Run:ai

# Introduction  The NVIDIA Run:ai Control-Plane API reference is a guide that provides an easy-to-use programming interface for adding various tasks to your application, including workload submission, resource management, and administrative operations.  NVIDIA Run:ai APIs are accessed using *bearer tokens*. To obtain a token, you need to create a **Service account** through the NVIDIA Run:ai user interface. To create a service account, in your UI, go to Access → Service Accounts (for organization-level service accounts) or User settings → Access Keys (for user access keys), and create a new one.  After you have created a new service account, you will need to assign it access rules. To assign access rules to the service account, see [Create access rules](https://run-ai-docs.nvidia.com/saas/infrastructure-setup/authentication/accessrules#create-or-delete-rules). Make sure you assign the correct rules to your service account. Use the [Roles](https://run-ai-docs.nvidia.com/saas/infrastructure-setup/authentication/roles) to assign the correct access rules.  To get your access token, follow the instructions in [Request a token](https://run-ai-docs.nvidia.com/saas/reference/api/rest-auth/#request-an-api-token).

The version of the OpenAPI document: latest
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


import unittest

from runai.api.nvidianim_api import NVIDIANIMApi


class TestNVIDIANIMApi(unittest.TestCase):
    """NVIDIANIMApi unit test stubs"""

    def setUp(self) -> None:
        self.api = NVIDIANIMApi()

    def tearDown(self) -> None:
        pass

    def test_create_nim_service(self) -> None:
        """Test case for create_nim_service

        Create a NVIDIA NIM service. [Experimental]
        """
        pass

    def test_get_nim_service_by_id(self) -> None:
        """Test case for get_nim_service_by_id

        Get a NVIDIA NIM service. [Experimental]
        """
        pass

    def test_update_nim_service_spec(self) -> None:
        """Test case for update_nim_service_spec

        Update NVIDIA NIM service spec. [Experimental]
        """
        pass


if __name__ == "__main__":
    unittest.main()
