# coding: utf-8

"""
NVIDIA Run:ai

# Introduction  The NVIDIA Run:ai Control-Plane API reference is a guide that provides an easy-to-use programming interface for adding various tasks to your application, including workload submission, resource management, and administrative operations.  NVIDIA Run:ai APIs are accessed using *bearer tokens*. To obtain a token, you need to create a **Service account** through the NVIDIA Run:ai user interface. To create a service account, in your UI, go to Access → Service Accounts (for organization-level service accounts) or User settings → Access Keys (for user access keys), and create a new one.  After you have created a new service account, you will need to assign it access rules. To assign access rules to the service account, see [Create access rules](https://run-ai-docs.nvidia.com/saas/infrastructure-setup/authentication/accessrules#create-or-delete-rules). Make sure you assign the correct rules to your service account. Use the [Roles](https://run-ai-docs.nvidia.com/saas/infrastructure-setup/authentication/roles) to assign the correct access rules.  To get your access token, follow the instructions in [Request a token](https://run-ai-docs.nvidia.com/saas/reference/api/rest-auth/#request-an-api-token).

The version of the OpenAPI document: latest
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


import unittest

import runai
from runai.models.inference_policy_defaults_v2_all_of_storage import (
    InferencePolicyDefaultsV2AllOfStorage,
)


class TestInferencePolicyDefaultsV2AllOfStorage(unittest.TestCase):
    """InferencePolicyDefaultsV2AllOfStorage unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> InferencePolicyDefaultsV2AllOfStorage:
        """Test InferencePolicyDefaultsV2AllOfStorage
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `InferencePolicyDefaultsV2AllOfStorage`

        # model = InferencePolicyDefaultsV2AllOfStorage()
        if include_optional:
            return InferencePolicyDefaultsV2AllOfStorage(
                config_map_volume=runai.models.config_maps_defaults.ConfigMapsDefaults(
                    attributes=runai.models.config_map_instance.ConfigMapInstance(),
                    instances=[runai.models.config_map_instance.ConfigMapInstance()],
                ),
                data_volume=runai.models.data_volumes_defaults.DataVolumesDefaults(
                    attributes=runai.models.data_volume_instance.DataVolumeInstance(),
                    instances=[runai.models.data_volume_instance.DataVolumeInstance()],
                ),
                empty_dir_volume=runai.models.empty_dirs_defaults.EmptyDirsDefaults(
                    attributes=runai.models.empty_dir_instance.EmptyDirInstance(),
                    instances=[runai.models.empty_dir_instance.EmptyDirInstance()],
                ),
                git=runai.models.gits_defaults.GitsDefaults(
                    attributes=runai.models.git_instance.GitInstance(),
                    instances=[runai.models.git_instance.GitInstance()],
                ),
                host_path=runai.models.host_paths_defaults.HostPathsDefaults(
                    attributes=runai.models.host_path_instance.HostPathInstance(),
                    instances=[runai.models.host_path_instance.HostPathInstance()],
                ),
                nfs=runai.models.nfss_defaults.NfssDefaults(
                    attributes=runai.models.nfs_instance.NfsInstance(),
                    instances=[runai.models.nfs_instance.NfsInstance()],
                ),
                pvc=runai.models.pvcs_defaults.PvcsDefaults(
                    attributes=runai.models.pvc_instance.PvcInstance(),
                    instances=[runai.models.pvc_instance.PvcInstance()],
                ),
                secret_volume=runai.models.secrets_defaults.SecretsDefaults(
                    attributes=runai.models.secret_instance2.SecretInstance2(),
                    instances=[runai.models.secret_instance2.SecretInstance2()],
                ),
            )
        else:
            return InferencePolicyDefaultsV2AllOfStorage()

    def testInferencePolicyDefaultsV2AllOfStorage(self):
        """Test InferencePolicyDefaultsV2AllOfStorage"""
        inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
