# coding: utf-8

"""
Test file for TokensApi
Generated by OpenAPI Generator with custom template
"""

import pytest
import unittest.mock as mock
from datetime import datetime, timezone
import json

from runai.configuration import Configuration
from runai.api_client import ApiClient
from runai.models import *
from runai.exceptions import ApiException


class TestTokensApi:
    """Test cases for TokensApi"""

    @pytest.fixture(autouse=True)
    def setup(self):
        """Setup test fixtures"""
        self.configuration = Configuration(
            client_id="test-client",
            client_secret="test-secret",
            runai_base_url="https://test.run.ai",
        )
        self.api_client = ApiClient(self.configuration)
        self.api = TokensApi(self.api_client)

        # Mock the request method
        self.request_patcher = mock.patch.object(self.api_client.rest_client, "request")
        self.mock_request = self.request_patcher.start()
        yield
        self.request_patcher.stop()

    def test_app_token(self):
        """Test case for app_token

        get application token Retrieve access token for an application. The application token is retrieved from the authorization server. This endpoint is deprecated.  Use /api/v1/token with the grantType parameter set to app_token instead, with AppID and appSecret set accordingly to get an application token
        """
        # Mock response
        mock_response = mock.Mock()
        mock_response.status = 200
        mock_response.read.return_value = json.dumps({"data": {}})
        self.mock_request.return_value = mock_response

        # Test parameters
        app_token_request = runai.AppTokenRequest()  # AppTokenRequest |

        # Make request
        response = self.api.app_token()

        # Verify request was made
        assert self.mock_request.called
        args, kwargs = self.mock_request.call_args

        # Verify request method and URL
        assert kwargs["method"] == "POST"
        assert "/v1/k8s/auth/oauth/apptoken" in kwargs["url"]

        # Verify body
        assert kwargs["body"] is not None

        # Verify response
        assert isinstance(response, AppTokenResponse)

    def test_app_token_error(self):
        """Test error handling for app_token"""
        # Mock error response
        mock_response = mock.Mock()
        mock_response.status = 400
        mock_response.read.return_value = json.dumps({"message": "Error message"})
        self.mock_request.return_value = mock_response

        # Test parameters

        # Verify error handling
        with pytest.raises(ApiException) as exc_info:
            self.api.app_token()
        assert exc_info.value.status == 400

    def test_grant_token(self):
        """Test case for grant_token

        Create an access token v1 Create tokens using the &#x60;grant_type&#x60; parameter.
        """
        # Mock response
        mock_response = mock.Mock()
        mock_response.status = 200
        mock_response.read.return_value = json.dumps({"data": {}})
        self.mock_request.return_value = mock_response

        # Test parameters
        token_request = {
            "grantType": "client_credentials",
            "clientID": "clientID",
            "clientSecret": "clientSecret",
        }  # TokenRequest |

        # Make request
        response = self.api.grant_token()

        # Verify request was made
        assert self.mock_request.called
        args, kwargs = self.mock_request.call_args

        # Verify request method and URL
        assert kwargs["method"] == "POST"
        assert "/api/v1/token" in kwargs["url"]

        # Verify body
        assert kwargs["body"] is not None

        # Verify response
        assert isinstance(response, TokenResponse)

    def test_grant_token_error(self):
        """Test error handling for grant_token"""
        # Mock error response
        mock_response = mock.Mock()
        mock_response.status = 400
        mock_response.read.return_value = json.dumps({"message": "Error message"})
        self.mock_request.return_value = mock_response

        # Test parameters

        # Verify error handling
        with pytest.raises(ApiException) as exc_info:
            self.api.grant_token()
        assert exc_info.value.status == 400

    def test_grant_token_v2(self):
        """Test case for grant_token_v2

        Create an access token v2 Use this endpoint to obtain an access token. Compliant with standard OAuth2 protocol and supports the common OAuth2 grant types.
        """
        # Mock response
        mock_response = mock.Mock()
        mock_response.status = 200
        mock_response.read.return_value = json.dumps({"data": {}})
        self.mock_request.return_value = mock_response

        # Test parameters
        grant_type = "grant_type_example"  # str | The OAuth2 grant type that determines how the token will be issued.
        client_id = "client_id_example"  # str | OAuth2 client identifier
        client_secret = "client_secret_example"  # str | OAuth2 client secret
        username = (
            "username_example"  # str | Resource owner username (for password grant)
        )
        password = "password_example"  # str | The password of the resource owner. Required only when using the password grant type.
        refresh_token = "refresh_token_example"  # str | The refresh token used to obtain a new access token. Required only when using the refresh_token grant type.
        code = "code_example"  # str | Authorization code issued by the authorization server. Used in the authorization_code grant to exchange the code for an access token.
        redirect_uri = "redirect_uri_example"  # str | The redirect URI used during the authorization request. Required for the authorization_code grant to validate the redirect destination.

        # Make request
        response = self.api.grant_token_v2(
            grant_type=grant_type,
        )

        # Verify request was made
        assert self.mock_request.called
        args, kwargs = self.mock_request.call_args

        # Verify request method and URL
        assert kwargs["method"] == "POST"
        assert "/api/v2/token" in kwargs["url"]

        # Verify response
        assert isinstance(response, OAuth2TokenResponse)

    def test_grant_token_v2_error(self):
        """Test error handling for grant_token_v2"""
        # Mock error response
        mock_response = mock.Mock()
        mock_response.status = 400
        mock_response.read.return_value = json.dumps({"message": "Error message"})
        self.mock_request.return_value = mock_response

        # Test parameters
        grant_type = "grant_type_example"

        # Verify error handling
        with pytest.raises(ApiException) as exc_info:
            self.api.grant_token_v2(
                grant_type=grant_type,
            )
        assert exc_info.value.status == 400
