# coding: utf-8

"""
NVIDIA Run:ai

# Introduction  The NVIDIA Run:ai Control-Plane API reference is a guide that provides an easy-to-use programming interface for adding various tasks to your application, including workload submission, resource management, and administrative operations.  NVIDIA Run:ai APIs are accessed using *bearer tokens*. To obtain a token, you need to create a **Service account** through the NVIDIA Run:ai user interface. To create a service account, in your UI, go to Access → Service Accounts (for organization-level service accounts) or User settings → Access Keys (for user access keys), and create a new one.  After you have created a new service account, you will need to assign it access rules. To assign access rules to the service account, see [Create access rules](https://run-ai-docs.nvidia.com/saas/infrastructure-setup/authentication/accessrules#create-or-delete-rules). Make sure you assign the correct rules to your service account. Use the [Roles](https://run-ai-docs.nvidia.com/saas/infrastructure-setup/authentication/roles) to assign the correct access rules.  To get your access token, follow the instructions in [Request a token](https://run-ai-docs.nvidia.com/saas/reference/api/rest-auth/#request-an-api-token).

The version of the OpenAPI document: latest
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


import unittest

import runai
from runai.models.host_paths_rules import HostPathsRules


class TestHostPathsRules(unittest.TestCase):
    """HostPathsRules unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> HostPathsRules:
        """Test HostPathsRules
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `HostPathsRules`

        # model = HostPathsRules()
        if include_optional:
            return HostPathsRules(
                attributes=runai.models.host_path_rules.HostPathRules(
                    path=runai.models.string_rules.StringRules(),
                    read_only=runai.models.boolean_rules.BooleanRules(
                        source_of_rule={"scope": "project", "projectId": 3},
                        required=True,
                        can_edit=True,
                    ),
                    mount_path=runai.models.string_rules.StringRules(),
                    mount_propagation=runai.models.host_path_mount_propagation_rules.HostPathMountPropagationRules(),
                ),
                instances=runai.models.item_rules.ItemRules(
                    source_of_rule={"scope": "project", "projectId": 3},
                    can_add=True,
                    locked=["HOME", "USER"],
                ),
            )
        else:
            return HostPathsRules()

    def testHostPathsRules(self):
        """Test HostPathsRules"""
        inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
