# coding: utf-8

"""
NVIDIA Run:ai

# Introduction  The NVIDIA Run:ai Control-Plane API reference is a guide that provides an easy-to-use programming interface for adding various tasks to your application, including workload submission, resource management, and administrative operations.  NVIDIA Run:ai APIs are accessed using *bearer tokens*. To obtain a token, you need to create a **Service account** through the NVIDIA Run:ai user interface. To create a service account, in your UI, go to Access → Service Accounts (for organization-level service accounts) or User settings → Access Keys (for user access keys), and create a new one.  After you have created a new service account, you will need to assign it access rules. To assign access rules to the service account, see [Create access rules](https://run-ai-docs.nvidia.com/saas/infrastructure-setup/authentication/accessrules#create-or-delete-rules). Make sure you assign the correct rules to your service account. Use the [Roles](https://run-ai-docs.nvidia.com/saas/infrastructure-setup/authentication/roles) to assign the correct access rules.  To get your access token, follow the instructions in [Request a token](https://run-ai-docs.nvidia.com/saas/reference/api/rest-auth/#request-an-api-token).

The version of the OpenAPI document: latest
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


import unittest

from runai.api.workload_templates_api import WorkloadTemplatesApi


class TestWorkloadTemplatesApi(unittest.TestCase):
    """WorkloadTemplatesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = WorkloadTemplatesApi()

    def tearDown(self) -> None:
        pass

    def test_count_templates(self) -> None:
        """Test case for count_templates

        Count templates. [Experimental]
        """
        pass

    def test_create_distributed_template(self) -> None:
        """Test case for create_distributed_template

        Create a new distributed training template. [Experimental]
        """
        pass

    def test_create_inference_template(self) -> None:
        """Test case for create_inference_template

        Create a new inference template. [Experimental]
        """
        pass

    def test_create_training_template(self) -> None:
        """Test case for create_training_template

        Create a new training template. [Experimental]
        """
        pass

    def test_create_workspace_template(self) -> None:
        """Test case for create_workspace_template

        Create a new workspace template. [Experimental]
        """
        pass

    def test_delete_distributed_template(self) -> None:
        """Test case for delete_distributed_template

        Delete a distributed training template by ID. [Experimental]
        """
        pass

    def test_delete_inference_template(self) -> None:
        """Test case for delete_inference_template

        Delete an inference template by ID. [Experimental]
        """
        pass

    def test_delete_training_template(self) -> None:
        """Test case for delete_training_template

        Delete a training template by ID. [Experimental]
        """
        pass

    def test_delete_workspace_template(self) -> None:
        """Test case for delete_workspace_template

        Delete a workspace template by ID. [Experimental]
        """
        pass

    def test_get_distributed_template(self) -> None:
        """Test case for get_distributed_template

        Get a specific distributed training template by ID. [Experimental]
        """
        pass

    def test_get_inference_template(self) -> None:
        """Test case for get_inference_template

        Get a specific inference template by ID. [Experimental]
        """
        pass

    def test_get_template_by_id1(self) -> None:
        """Test case for get_template_by_id1

        Get a template, any type. [Experimental]
        """
        pass

    def test_get_training_template(self) -> None:
        """Test case for get_training_template

        Retrieve a specific training template by ID. [Experimental]
        """
        pass

    def test_get_workspace_template(self) -> None:
        """Test case for get_workspace_template

        Retrieve a specific workspace template by ID. [Experimental]
        """
        pass

    def test_list_distributed_templates(self) -> None:
        """Test case for list_distributed_templates

        List all distributed training templates. [Experimental]
        """
        pass

    def test_list_inference_templates(self) -> None:
        """Test case for list_inference_templates

        List all inference templates. [Experimental]
        """
        pass

    def test_list_templates1(self) -> None:
        """Test case for list_templates1

        List templates. [Experimental]
        """
        pass

    def test_list_training_templates(self) -> None:
        """Test case for list_training_templates

        List all training templates. [Experimental]
        """
        pass

    def test_list_workspace_templates(self) -> None:
        """Test case for list_workspace_templates

        List all workspace templates. [Experimental]
        """
        pass

    def test_patch_distributed_template(self) -> None:
        """Test case for patch_distributed_template

        Patch a distributed training template by ID. [Experimental]
        """
        pass

    def test_patch_training_template(self) -> None:
        """Test case for patch_training_template

        Patch a training template by ID. [Experimental]
        """
        pass

    def test_patch_workspace_template(self) -> None:
        """Test case for patch_workspace_template

        Patch a workspace template by ID. [Experimental]
        """
        pass

    def test_template_name_availability(self) -> None:
        """Test case for template_name_availability

        Template name availability
        """
        pass

    def test_update_distributed_template(self) -> None:
        """Test case for update_distributed_template

        Update a distributed training template by ID. [Experimental]
        """
        pass

    def test_update_training_template(self) -> None:
        """Test case for update_training_template

        Update a training template by ID. [Experimental]
        """
        pass

    def test_update_workspace_template(self) -> None:
        """Test case for update_workspace_template

        Update a workspace template by ID. [Experimental]
        """
        pass


if __name__ == "__main__":
    unittest.main()
