# coding: utf-8

"""
NVIDIA Run:ai

# Introduction  The NVIDIA Run:ai Control-Plane API reference is a guide that provides an easy-to-use programming interface for adding various tasks to your application, including workload submission, resource management, and administrative operations.  NVIDIA Run:ai APIs are accessed using *bearer tokens*. To obtain a token, you need to create a **Service account** through the NVIDIA Run:ai user interface. To create a service account, in your UI, go to Access → Service Accounts (for organization-level service accounts) or User settings → Access Keys (for user access keys), and create a new one.  After you have created a new service account, you will need to assign it access rules. To assign access rules to the service account, see [Create access rules](https://run-ai-docs.nvidia.com/saas/infrastructure-setup/authentication/accessrules#create-or-delete-rules). Make sure you assign the correct rules to your service account. Use the [Roles](https://run-ai-docs.nvidia.com/saas/infrastructure-setup/authentication/roles) to assign the correct access rules.  To get your access token, follow the instructions in [Request a token](https://run-ai-docs.nvidia.com/saas/reference/api/rest-auth/#request-an-api-token).

The version of the OpenAPI document: latest
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


import unittest

import runai
from runai.models.department1_current_project_resources_inner import (
    Department1CurrentProjectResourcesInner,
)


class TestDepartment1CurrentProjectResourcesInner(unittest.TestCase):
    """Department1CurrentProjectResourcesInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(
        self, include_optional
    ) -> Department1CurrentProjectResourcesInner:
        """Test Department1CurrentProjectResourcesInner
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `Department1CurrentProjectResourcesInner`

        # model = Department1CurrentProjectResourcesInner()
        if include_optional:
            return Department1CurrentProjectResourcesInner(
                number_of_pending_workloads=1,
                gpu=runai.models.resource_data.ResourceData(
                    quota=3,
                    allocated=2.5,
                    utilization=0.765,
                ),
                cpu=runai.models.resource_data.ResourceData(
                    quota=3,
                    allocated=2.5,
                    utilization=0.765,
                ),
                memory=runai.models.resource_data.ResourceData(
                    quota=3,
                    allocated=2.5,
                    utilization=0.765,
                ),
                project_name="project-a",
                nodepool_name="nodepoola",
            )
        else:
            return Department1CurrentProjectResourcesInner(
                number_of_pending_workloads=1,
                gpu=runai.models.resource_data.ResourceData(
                    quota=3,
                    allocated=2.5,
                    utilization=0.765,
                ),
                cpu=runai.models.resource_data.ResourceData(
                    quota=3,
                    allocated=2.5,
                    utilization=0.765,
                ),
                memory=runai.models.resource_data.ResourceData(
                    quota=3,
                    allocated=2.5,
                    utilization=0.765,
                ),
                project_name="project-a",
                nodepool_name="nodepoola",
            )

    def testDepartment1CurrentProjectResourcesInner(self):
        """Test Department1CurrentProjectResourcesInner"""
        inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
