# coding: utf-8

"""
NVIDIA Run:ai

# Introduction  The NVIDIA Run:ai Control-Plane API reference is a guide that provides an easy-to-use programming interface for adding various tasks to your application, including workload submission, resource management, and administrative operations.  NVIDIA Run:ai APIs are accessed using *bearer tokens*. To obtain a token, you need to create an **Application** through the NVIDIA Run:ai user interface. To create an application, in your UI, go to `Settings & Tools`, `Application` and create a new Application.  After you have created a new application, you will need to assign it access rules. To assign access rules to the application, see [Create access rules](https://run-ai-docs.nvidia.com/saas/infrastructure-setup/authentication/accessrules#create-or-delete-rules). Make sure you assign the correct rules to your application. Use the [Roles](https://run-ai-docs.nvidia.com/saas/infrastructure-setup/authentication/roles) to assign the correct access rules.  To get your access token, follow the instructions in [Request a token](https://run-ai-docs.nvidia.com/saas/reference/api/rest-auth/#request-an-api-token).

The version of the OpenAPI document: latest
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictBool
from typing import Any, ClassVar, Dict, List, Optional
from runai.models.email_notifications_state import EmailNotificationsState
from runai.models.slack_notifications_state import SlackNotificationsState
from typing import Optional, Set
from typing_extensions import Self


class NotificationState(BaseModel):
    """
    Pydantic class model representing NotificationState.

    Parameters:
        ```python
        enabled: bool
        email: EmailNotificationsState
        slack: SlackNotificationsState
        ```
        enabled: See model bool for more information. - Default: False
        email: See model EmailNotificationsState for more information.
        slack: See model SlackNotificationsState for more information.
    Example:
        ```python
        NotificationState(
            enabled=True,
                        email=runai.models.email_notifications_state.EmailNotificationsState(
                    enabled = True, ),
                        slack=runai.models.slack_notifications_state.SlackNotificationsState(
                    enabled = True,
                    workspace_name = '', )
        )
        ```
    """  # noqa: E501

    enabled: StrictBool
    email: Optional[EmailNotificationsState] = None
    slack: Optional[SlackNotificationsState] = None
    __properties: ClassVar[List[str]] = ["enabled", "email", "slack"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of NotificationState from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: Set[str] = set(
            [
                "enabled",
            ]
        )

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of email
        if self.email:
            _dict["email"] = self.email.to_dict()
        # override the default output from pydantic by calling `to_dict()` of slack
        if self.slack:
            _dict["slack"] = self.slack.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of NotificationState from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "enabled": (
                    obj.get("enabled") if obj.get("enabled") is not None else False
                ),
                "email": (
                    EmailNotificationsState.from_dict(obj["email"])
                    if obj.get("email") is not None
                    else None
                ),
                "slack": (
                    SlackNotificationsState.from_dict(obj["slack"])
                    if obj.get("slack") is not None
                    else None
                ),
            }
        )
        return _obj
